const ADD_INGREDIENT = 'ADD_INGREDIENT';
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
const SET_INGREDIENTS = 'SET_INGREDIENTS';
const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export {
    ADD_INGREDIENT,
    REMOVE_INGREDIENT,
    SET_INGREDIENTS,
    FETCH_INGREDIENTS_FAILED
}

