const ADD_INGREDIENT = 'ADD_INGREDIENT';
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
const SET_INGREDIENTS = 'SET_INGREDIENTS';
const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';

export {
    ADD_INGREDIENT,
    REMOVE_INGREDIENT,
    SET_INGREDIENTS,
    FETCH_INGREDIENTS_FAILED,
    PURCHASE_BURGER_SUCCESS,
    PURCHASE_BURGER_FAILED,
    PURCHASE_BURGER_START
}

