const ADD_INGREDIENT = 'ADD_INGREDIENT';
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
const SET_INGREDIENTS = 'SET_INGREDIENTS';
const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';

const PURCHASE_BURGER = 'PURCHASE_BURGER';
const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT';

const FETCH_ORDERS = 'FETCH_ORDERS';
const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export {
    ADD_INGREDIENT,
    REMOVE_INGREDIENT,
    INIT_INGREDIENTS,
    SET_INGREDIENTS,
    FETCH_INGREDIENTS_FAIL,
    PURCHASE_BURGER,
    PURCHASE_BURGER_SUCCESS,
    PURCHASE_BURGER_FAIL,
    PURCHASE_BURGER_START,
    PURCHASE_BURGER_INIT,
    FETCH_ORDERS,
    FETCH_ORDERS_SUCCESS,
    FETCH_ORDERS_FAIL,
    FETCH_ORDERS_START
}

